<a href="https://colab.research.google.com/github/javajerry/PyTorch/blob/main/PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install torch torchvision torchaudio

     |████████████████████████████████| 7.6MB 4.7MB/s 
ERROR: torchaudio 0.7.2 has requirement torch==1.7.1, but you'll have torch 1.7.0+cu101 which is incompatible.


In [3]:
# Let's import the torch module to get started.
import torch

##Tensors
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.



In [7]:
t1 = torch.tensor(4.)
print(t1)
print(t1.dtype)

tensor(4.)
torch.float32


## Complex Tensor

In [8]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

## Matrix

In [9]:
t3 = torch.tensor([[5.,6],
                    [7,8],
                    [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

##Tensor operations and gradients
We can combine tensors with the usual arithmetic operations. 

In [10]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [11]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [12]:
# Compute derivatives
y.backward()


The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [13]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x, i.e., 3, and dy/db has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

##Tensor functions
Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors.

In [14]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])